=== Elias-elf/Museum-Data-Structure/XML/schemas/Restoration.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name='Restoration'>
		<xs:complexType>
			<xs:sequence>
				<xs:element name="Project" type='ProjectType' minOccurs="1" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:simpleType name="LoanAmountType">
		<xs:restriction base="xs:positiveInteger">
			<xs:minInclusive value="5000"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:complexType name="ProjectType">
		<xs:sequence>
			<xs:element name="Loan">
				<xs:complexType>
					<xs:simpleContent>
						<xs:extension base="LoanAmountType">
							<xs:attribute name="currency" type="xs:string" use="required" fixed="EUR"/>
						</xs:extension>
					</xs:simpleContent>
				</xs:complexType>
			</xs:element>
			<xs:element name="Artifacts">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="Artifact" minOccurs="1" maxOccurs="unbounded">
							<xs:complexType>
								<xs:attribute name="ref" type="xs:IDREF" use="required"/>
							</xs:complexType>
						</xs:element>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
			<xs:element name="Responsible">
				<xs:complexType>
					<xs:sequence>
						<xs:element name='FullName' type='xs:string'/>
						<xs:element name='Domain'>
							<xs:simpleType>
								<xs:restriction base="xs:string">
									<xs:enumeration value="Material"/>
									<xs:enumeration value="CulturalHeritage"/>
									<xs:enumeration value="Provenance"/>
									<xs:enumeration value="Collection"/>
								</xs:restriction>
							</xs:simpleType>
						</xs:element>
						<xs:element name='Expertise' type='xs:string'/>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
		</xs:sequence>
		<xs:attribute name="id" type="xs:ID" use="required"/>
	</xs:complexType>
</xs:schema>

=== Elias-elf/Museum-Data-Structure/XML/Restoration.xml
<?xml version='1.0' encoding='UTF-8'?>
<Restoration xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="Restoration.xsd">
  <Project id="RP001">
    <Loan currency="EUR">27750</Loan>
    <Artifacts>
      <Artifact ref="A0004"/>
      <Artifact ref="A0008"/>
      <Artifact ref="A0020"/>
    </Artifacts>
    <Responsible>
      <FullName>Leila Haddad</FullName>
      <Domain>Material</Domain>
      <Expertise>Ceramic Expert</Expertise>
    </Responsible>
  </Project>
  <Project id="RP002">
    <Loan currency="EUR">30500</Loan>
    <Artifacts>
      <Artifact ref="A0085"/>
      <Artifact ref="A0086"/>
      <Artifact ref="A0087"/>
      <Artifact ref="A0088"/>
    </Artifacts>
    <Responsible>
      <FullName>Marco Rossi</FullName>
      <Domain>CulturalHeritage</Domain>
      <Expertise>Ancient Greek Cultural Heritage Expert</Expertise>
    </Responsible>
  </Project>
  <Project id="RP003">
    <Loan currency="EUR">33250</Loan>
    <Artifacts>
      <Artifact ref="A0001"/>
      <Artifact ref="A0003"/>
      <Artifact ref="A0005"/>
      <Artifact ref="A0006"/>
      <Artifact ref="A0007"/>
    </Artifacts>
    <Responsible>
      <FullName>Amina Diallo</FullName>
      <Domain>Provenance</Domain>
      <Expertise>Egypt Provenance Expert</Expertise>
    </Responsible>
  </Project>
  <Project id="RP004">
    <Loan currency="EUR">36000</Loan>
    <Artifacts>
      <Artifact ref="A0002"/>
      <Artifact ref="A0009"/>
    </Artifacts>
    <Responsible>
      <FullName>Hiroshi Tanaka</FullName>
      <Domain>Collection</Domain>
      <Expertise>Archaeological Objects Expert</Expertise>
    </Responsible>
  </Project>
  <Project id="RP005">
    <Loan currency="EUR">38750</Loan>
    <Artifacts>
      <Artifact ref="A0011"/>
      <Artifact ref="A0018"/>
      <Artifact ref="A0027"/>
    </Artifacts>
    <Responsible>
      <FullName>Sofia Alvarez</FullName>
      <Domain>Material</Domain>
      <Expertise>Gold Expert</Expertise>
    </Responsible>
  </Project>
  <Project id="RP006">
    <Loan currency="EUR">41500</Loan>
    <Artifacts>
      <Artifact ref="A0169"/>
      <Artifact ref="A0170"/>
      <Artifact ref="A0171"/>
      <Artifact ref="A0172"/>
    </Artifacts>
    <Responsible>
      <FullName>Daniel Okafor</FullName>
      <Domain>CulturalHeritage</Domain>
      <Expertise>Roman and Byzantine Cultural Heritage Expert</Expertise>
    </Responsible>
  </Project>
  <Project id="RP007">
    <Loan currency="EUR">44250</Loan>
    <Artifacts>
      <Artifact ref="A0586"/>
      <Artifact ref="A0587"/>
      <Artifact ref="A0588"/>
      <Artifact ref="A0589"/>
      <Artifact ref="A0590"/>
    </Artifacts>
    <Responsible>
      <FullName>Mei Lin Chen</FullName>
      <Domain>Provenance</Domain>
      <Expertise>Japan Provenance Expert</Expertise>
    </Responsible>
  </Project>
  <Project id="RP008">
    <Loan currency="EUR">47000</Loan>
    <Artifacts>
      <Artifact ref="A0024"/>
      <Artifact ref="A0032"/>
    </Artifacts>
    <Responsible>
      <FullName>Nadia Rahman</FullName>
      <Domain>Collection</Domain>
      <Expertise>Ceramics and Terracotta Expert</Expertise>
    </Responsible>
  </Project>
  <Project id="RP009">
    <Loan currency="EUR">49750</Loan>
    <Artifacts>
      <Artifact ref="A0015"/>
      <Artifact ref="A0025"/>
      <Artifact ref="A0028"/>
    </Artifacts>
    <Responsible>
      <FullName>Thomas Weber</FullName>
      <Domain>Material</Domain>
      <Expertise>Wood Expert</Expertise>
    </Responsible>
  </Project>
  <Project id="RP010">
    <Loan currency="EUR">52500</Loan>
    <Artifacts>
      <Artifact ref="A0253"/>
      <Artifact ref="A0254"/>
      <Artifact ref="A0255"/>
      <Artifact ref="A0256"/>
    </Artifacts>
    <Responsible>
      <FullName>Priya Nair</FullName>
      <Domain>CulturalHeritage</Domain>
      <Expertise>Medieval European Cultural Heritage Expert</Expertise>
    </Responsible>
  </Project>
  <Project id="RP011">
    <Loan currency="EUR">55250</Loan>
    <Artifacts>
      <Artifact ref="A0503"/>
      <Artifact ref="A0504"/>
      <Artifact ref="A0505"/>
      <Artifact ref="A0506"/>
      <Artifact ref="A0507"/>
    </Artifacts>
    <Responsible>
      <FullName>Elena Petrova</FullName>
      <Domain>Provenance</Domain>
      <Expertise>China Provenance Expert</Expertise>
    </Responsible>
  </Project>
  <Project id="RP012">
    <Loan currency="EUR">58000</Loan>
    <Artifacts>
      <Artifact ref="A0193"/>
      <Artifact ref="A0194"/>
    </Artifacts>
    <Responsible>
      <FullName>Gabriel Martin</FullName>
      <Domain>Collection</Domain>
      <Expertise>Medieval Worlds Expert</Expertise>
    </Responsible>
  </Project>
  <Project id="RP013">
    <Loan currency="EUR">60750</Loan>
    <Artifacts>
      <Artifact ref="A0039"/>
      <Artifact ref="A0103"/>
      <Artifact ref="A0105"/>
    </Artifacts>
    <Responsible>
      <FullName>Yuki Sato</FullName>
      <Domain>Material</Domain>
      <Expertise>Silver Expert</Expertise>
    </Responsible>
  </Project>
  <Project id="RP014">
    <Loan currency="EUR">63500</Loan>
    <Artifacts>
      <Artifact ref="A0337"/>
      <Artifact ref="A0338"/>
      <Artifact ref="A0339"/>
      <Artifact ref="A0340"/>
    </Artifacts>
    <Responsible>
      <FullName>Maya Thompson</FullName>
      <Domain>CulturalHeritage</Domain>
      <Expertise>Renaissance and Baroque European Cultural Heritage Expert</Expertise>
    </Responsible>
  </Project>
  <Project id="RP015">
    <Loan currency="EUR">66250</Loan>
    <Artifacts>
      <Artifact ref="A0057"/>
      <Artifact ref="A0127"/>
      <Artifact ref="A0229"/>
      <Artifact ref="A0239"/>
      <Artifact ref="A0260"/>
    </Artifacts>
    <Responsible>
      <FullName>Omar Khalil</FullName>
      <Domain>Provenance</Domain>
      <Expertise>Italy Provenance Expert</Expertise>
    </Responsible>
  </Project>
  <Project id="RP016">
    <Loan currency="EUR">69000</Loan>
    <Artifacts>
      <Artifact ref="A0019"/>
      <Artifact ref="A0026"/>
    </Artifacts>
    <Responsible>
      <FullName>Lucia Ferreira</FullName>
      <Domain>Collection</Domain>
      <Expertise>Vessels and Containers Expert</Expertise>
    </Responsible>
  </Project>
  <Project id="RP017">
    <Loan currency="EUR">71750</Loan>
    <Artifacts>
      <Artifact ref="A0010"/>
      <Artifact ref="A0012"/>
      <Artifact ref="A0014"/>
    </Artifacts>
    <Responsible>
      <FullName>Samuel Mensah</FullName>
      <Domain>Material</Domain>
      <Expertise>Stone Expert</Expertise>
    </Responsible>
  </Project>
  <Project id="RP018">
    <Loan currency="EUR">74500</Loan>
    <Artifacts>
      <Artifact ref="A0420"/>
      <Artifact ref="A0421"/>
      <Artifact ref="A0422"/>
      <Artifact ref="A0423"/>
    </Artifacts>
    <Responsible>
      <FullName>Anika Shah</FullName>
      <Domain>CulturalHeritage</Domain>
      <Expertise>Islamic Cultural Heritage Expert</Expertise>
    </Responsible>
  </Project>
  <Project id="RP019">
    <Loan currency="EUR">77250</Loan>
    <Artifacts>
      <Artifact ref="A0262"/>
      <Artifact ref="A0267"/>
      <Artifact ref="A0274"/>
      <Artifact ref="A0275"/>
      <Artifact ref="A0278"/>
    </Artifacts>
    <Responsible>
      <FullName>Claire Dubois</FullName>
      <Domain>Provenance</Domain>
      <Expertise>France Provenance Expert</Expertise>
    </Responsible>
  </Project>
  <Project id="RP020">
    <Loan currency="EUR">80000</Loan>
    <Artifacts>
      <Artifact ref="A0016"/>
      <Artifact ref="A0021"/>
    </Artifacts>
    <Responsible>
      <FullName>David Kim</FullName>
      <Domain>Collection</Domain>
      <Expertise>Sculpture and Relief Expert</Expertise>
    </Responsible>
  </Project>
  <Project id="RP021">
    <Loan currency="EUR">82750</Loan>
    <Artifacts>
      <Artifact ref="A0084"/>
      <Artifact ref="A0093"/>
      <Artifact ref="A0122"/>
    </Artifacts>
    <Responsible>
      <FullName>Leila Haddad</FullName>
      <Domain>Material</Domain>
      <Expertise>Bronze Expert</Expertise>
    </Responsible>
  </Project>
  <Project id="RP022">
    <Loan currency="EUR">85500</Loan>
    <Artifacts>
      <Artifact ref="A0669"/>
      <Artifact ref="A0670"/>
      <Artifact ref="A0671"/>
      <Artifact ref="A0672"/>
    </Artifacts>
    <Responsible>
      <FullName>Marco Rossi</FullName>
      <Domain>CulturalHeritage</Domain>
      <Expertise>South and Southeast Asian Cultural Heritage Expert</Expertise>
    </Responsible>
  </Project>
  <Project id="RP023">
    <Loan currency="EUR">88250</Loan>
    <Artifacts>
      <Artifact ref="A0924"/>
      <Artifact ref="A0926"/>
      <Artifact ref="A0935"/>
      <Artifact ref="A0937"/>
      <Artifact ref="A0940"/>
    </Artifacts>
    <Responsible>
      <FullName>Amina Diallo</FullName>
      <Domain>Provenance</Domain>
      <Expertise>Peruvian North Coast Provenance Expert</Expertise>
    </Responsible>
  </Project>
  <Project id="RP024">
    <Loan currency="EUR">91000</Loan>
    <Artifacts>
      <Artifact ref="A0013"/>
      <Artifact ref="A0017"/>
    </Artifacts>
    <Responsible>
      <FullName>Hiroshi Tanaka</FullName>
      <Domain>Collection</Domain>
      <Expertise>Ancient Worlds Expert</Expertise>
    </Responsible>
  </Project>
  <Project id="RP025">
    <Loan currency="EUR">93750</Loan>
    <Artifacts>
      <Artifact ref="A0056"/>
      <Artifact ref="A0060"/>
      <Artifact ref="A0076"/>
    </Artifacts>
    <Responsible>
      <FullName>Sofia Alvarez</FullName>
      <Domain>Material</Domain>
      <Expertise>Glass Expert</Expertise>
    </Responsible>
  </Project>
  <Project id="RP026">
    <Loan currency="EUR">96500</Loan>
    <Artifacts>
      <Artifact ref="A0752"/>
      <Artifact ref="A0753"/>
      <Artifact ref="A0754"/>
      <Artifact ref="A0755"/>
    </Artifacts>
    <Responsible>
      <FullName>Daniel Okafor</FullName>
      <Domain>CulturalHeritage</Domain>
